import { COMPANIONS, ORIGINS } from '../data/origins.ts';
import { ENDINGS } from '../data/story.ts';
import { createGame, growthOf, levelOf } from '../game/state.ts';
import type { GameState, Origin, Region } from '../game/types.ts';
import { companionSprite, portraitUrl } from '../render/sprites.ts';
import { button, escape } from './kit.ts';
import { icon, wolfMark } from './icons.ts';

export const CINEMATIC: { region: Region; title: string; line: string; sub: string }[] = [
  { region: 'mine', title: 'BENEATH', line: 'They gave us a world without a sky.', sub: 'MARS · THE BURIED WARDS' },
  { region: 'citadel', title: 'ABOVE', line: 'And called the distance between us destiny.', sub: 'THE AUREATE SPIRES' },
  { region: 'tundra', title: 'BEYOND', line: 'But even a god can be a voice behind a door.', sub: 'THE POLAR EXCLUSION ZONE' },
  { region: 'hollow', title: 'TOGETHER', line: 'A fire. A name. A promise to come back.', sub: 'SOMEWHERE THE MAPS FORGOT' },
  { region: 'moon', title: 'BECOMING', line: 'The wolf is not what you were born.', sub: 'IT IS WHAT YOU CHOOSE TO BECOME.' },
];

export function cinematicScreen(index: number): string {
  const frame = CINEMATIC[index];
  return `<main id="content" class="cinematic-screen" tabindex="-1"><div id="scene-slot" class="cinematic-scene scene-slot"></div><div class="cinematic-shade"></div><header class="cinematic-header">${wolfMark()}<span>OMNIS VIR LUPUS</span>${button('Skip intro', 'skip-intro', { className: 'subtle', icon: 'arrow' })}</header><div class="cinematic-caption" key="${index}"><span class="eyebrow">${frame.sub}</span><h1>${frame.title}</h1><p>${frame.line}</p></div><div class="cinematic-progress">${CINEMATIC.map((_, n) => `<i class="${n <= index ? 'filled' : ''}"></i>`).join('')}</div><span class="cinematic-note">AN INDEPENDENT RED RISING FAN STORY</span></main>`;
}

export function titleScreen(state: GameState | null, saveWarning: string | null): string {
  return `<main id="content" class="title-screen" tabindex="-1"><div id="scene-slot" class="title-scene scene-slot"></div><div class="title-shade"></div><header class="title-top"><div>${wolfMark()}<span>A WORLD AFTER WOLVES</span></div><button class="text-button" data-action="credits">An independent fan game ${icon('arrow')}</button></header>
    <div class="title-content"><div class="title-ornament"><i></i>${icon('star')}<i></i></div><span class="eyebrow">THREE BEGINNINGS. ONE IMPOSSIBLE SKY.</span><h1>OMNIS<br><span>VIR LUPUS</span></h1><p class="title-translation">Every man a wolf.</p><div class="title-line"></div><p class="title-description">Tend to a life. Temper a blade.<br>Choose what survives the revolution.</p><div class="title-actions">
      ${state ? button(`Continue as ${state.name}`, 'load-game', { className: 'primary title-play', icon: 'arrow' }) : button('Begin your story', 'new-game', { className: 'primary title-play', icon: 'arrow' })}
      <div>${state ? button('New beginning', 'new-game', { className: 'subtle' }) : ''}${button('Import a save', 'import', { className: 'subtle', icon: 'upload' })}${button('Watch prologue', 'replay-intro', { className: 'subtle' })}</div>
    </div>${state ? `<div class="continue-note"><i class="status-dot"></i>${escape(ORIGINS[state.origin].name)} origin · ${growthOf(state).name} · Level ${levelOf(state)}</div>` : ''}${saveWarning ? `<p class="save-warning">${escape(saveWarning)}</p>` : ''}</div>
    <footer class="title-footer"><span class="age-badge">16+</span><p>FICTIONAL VIOLENCE · OPPRESSION · LOSS<br><span>Intended audience guidance. Not an official age classification.</span></p><div><span>FREE TO PLAY. FREE TO KEEP.</span><small>Original fan story inspired by Pierce Brown’s Red Rising.</small></div></footer>
  </main>`;
}

export function creationScreen(selected: Origin, name = ''): string {
  const origin = ORIGINS[selected];
  return `<main id="content" class="creation-screen" tabindex="-1"><header class="creation-top"><button class="text-button" data-action="title">${icon('back')}Back to the beginning</button><div>${wolfMark()}<span>OMNIS VIR LUPUS</span></div></header><div class="creation-heading"><span class="eyebrow">YOUR ORIGIN IS ONLY THE FIRST CHAPTER</span><h1>Where does your wolf begin?</h1><p>Three lives shaped by the same world. Choose the one you will change.</p></div>
    <div class="origin-grid" role="group" aria-label="Choose your character origin">${(['red', 'gold', 'obsidian'] as Origin[]).map(id => {
      const entry = ORIGINS[id];
      const preview = createGame('Preview', id, 1, 1);
      return `<button class="origin-card ${id} ${selected === id ? 'selected' : ''}" data-action="origin" data-origin="${id}" aria-pressed="${selected === id}"><span class="origin-selection">${selected === id ? icon('check') : '<i></i>'}</span><span class="origin-number">${id === 'red' ? '01' : id === 'gold' ? '02' : '03'}</span><div class="origin-portrait"><div class="portrait-halo"></div><img src="${portraitUrl(preview)}" alt="${entry.name} character"></div><span class="eyebrow">${entry.home.toUpperCase()}</span><h2>${entry.name}</h2><h3>${entry.title}</h3><p>${entry.description}</p><span class="origin-trait">${icon(id === 'red' ? 'heart' : id === 'gold' ? 'sun' : 'shield')}${entry.trait}</span></button>`;
    }).join('')}</div>
    <div class="creation-bottom panel"><div class="origin-promise"><span class="eyebrow">${origin.name.toUpperCase()} · THE ROAD AHEAD</span><p>${origin.promise}</p></div><form id="creation-form"><label for="character-name">WHAT WILL THEY CALL YOU?</label><div><input id="character-name" name="name" type="text" maxlength="24" autocomplete="off" required placeholder="Your character’s name" value="${escape(name)}" aria-describedby="name-note"><button type="submit" class="button primary">Begin as ${selected === 'obsidian' ? 'an Obsidian' : `a ${origin.name}`}${icon('arrow')}</button></div><small id="name-note">A new life begins at sixteen. Your progress stays on this device.</small></form></div><p class="creation-note">An original, noncommercial fan story. All Red Rising story inspiration, setting, and original series characters are credited to Pierce Brown.</p>
  </main>`;
}

export function tutorialContent(state: GameState): string {
  return `<div class="guide-header">${wolfMark()}<span class="eyebrow">WELCOME TO THE HOLLOW</span><h2>A person first.<br>A wolf when you must.</h2><p>${escape(state.name)}, this is your place between battles. Here’s what will get you through the first night.</p></div><div class="guide-steps"><div><span>01</span><div><h3>Care is preparation.</h3><p>Eat, rest, train, and talk at camp. Good care strengthens you. Time away never kills your character.</p></div></div><div><span>02</span><div><h3>Follow the story.</h3><p>Continue the current operation, make choices, and face encounters. You can return to camp between fights and resume your checkpoint.</p></div></div><div><span>03</span><div><h3>Read the next move.</h3><p>Enemies show their intentions. Hit a weakness or use Sunder to break a shield. Guard against charged attacks. Build three charges, then activate Burst.</p></div></div><div><span>04</span><div><h3>Keep what matters.</h3><p>Every committed action saves automatically. Use Settings to export a backup, change difficulty, or reduce motion.</p></div></div></div>${button('Make yourself at home', 'tutorial-done', { className: 'primary full-width', icon: 'camp' })}`;
}

export function settingsContent(state: GameState | null, durable: boolean, warning: string | null): string {
  return `<span class="eyebrow">MAKE THIS YOURS</span><h2>Settings & saves</h2>
  ${state ? `<div class="settings-section"><h3>The experience</h3><label class="setting-row"><span><strong>Sound effects</strong><small>Blades, fire, and small discoveries.</small></span><input type="checkbox" data-setting="sound" ${state.settings.sound ? 'checked' : ''}></label><label class="setting-row"><span><strong>Music</strong><small>An original, synthesized score.</small></span><input type="checkbox" data-setting="music" ${state.settings.music ? 'checked' : ''}></label><label class="setting-row"><span><strong>Volume</strong></span><input type="range" min="0" max="1" step=".05" value="${state.settings.volume}" data-setting="volume" aria-label="Volume"></label><label class="setting-row"><span><strong>Reduced motion</strong><small>Quiet particles, flashes, walking, and camera shake.</small></span><input type="checkbox" data-setting="reducedMotion" ${state.settings.reducedMotion ? 'checked' : ''}></label><label class="setting-row"><span><strong>Larger text</strong><small>A little more room for the story.</small></span><input type="checkbox" data-setting="textSize" ${state.settings.textSize === 'large' ? 'checked' : ''}></label><label class="setting-row"><span><strong>Difficulty</strong><small>Changes future encounters. Your current battle stays consistent.</small></span><select data-setting="difficulty"><option value="story" ${state.settings.difficulty === 'story' ? 'selected' : ''}>Story · gentler battles</option><option value="standard" ${state.settings.difficulty === 'standard' ? 'selected' : ''}>Standard · intended balance</option><option value="veteran" ${state.settings.difficulty === 'veteran' ? 'selected' : ''}>Veteran · harder battles</option></select></label><label class="setting-row"><span><strong>Battle animations</strong></span><select data-setting="battleSpeed"><option value="1" ${state.settings.battleSpeed === 1 ? 'selected' : ''}>1× · cinematic</option><option value="2" ${state.settings.battleSpeed === 2 ? 'selected' : ''}>2× · swift</option></select></label></div>` : ''}
  <div class="settings-section"><h3>Your progress</h3><p class="${warning ? 'save-warning' : 'muted'}">${escape(warning ?? (durable ? 'Your latest checkpoint is saved on this device. Export a file to keep a backup or move to another device.' : 'Progress is stored in this browser. Keep a backup before clearing site data.'))}</p><div class="settings-save-actions">${state ? button('Export save', 'export', { icon: 'download' }) : ''}${button('Import save', 'import', { icon: 'upload' })}${button('Previous checkpoint', 'restore', { icon: 'clock', disabled: !state })}</div><p class="panel-note">No account, tracking, or cloud subscription. Browser storage can be cleared by your browser; an exported file is your portable backup.</p></div>
  <div class="settings-section settings-links">${button('Field guide', 'help', { icon: 'book', className: 'subtle' })}${button('Credits', 'credits', { icon: 'feather', className: 'subtle' })}${state ? button('Return to title', 'title', { icon: 'back', className: 'subtle' }) : ''}</div>`;
}

export function creditsContent(): string {
  return `<div class="credits-heading">${wolfMark()}<span class="eyebrow">AN INDEPENDENT FAN PROJECT</span><h2>Omnis Vir Lupus</h2><p>Every man a wolf.</p></div><div class="credits-copy"><h3>With thanks to Pierce Brown</h3><p>This is an unofficial, noncommercial fan game inspired by the <em>Red Rising</em> book series. All credit for the original series, its world, Colors, story inspiration, and original characters belongs to Pierce Brown and the respective rights holders.</p><p>This project is not affiliated with, endorsed by, or an official adaptation from Pierce Brown, his publishers, or other rights holders. Its protagonist, campaign dialogue, companions, artwork, and synthesized music were created for this fan project. It does not reproduce passages, official illustrations, or recordings from the books.</p><h3>Free, open tools</h3><p>Phaser · TypeScript · Vite · Web Audio<br>Original pixel art rendered in code.<br>Cinzel & Barlow fonts, SIL Open Font License.</p><h3>Made for a more mature story</h3><p>Intended for ages 16 and up: stylized fictional combat, oppression, loss, and non-graphic descriptions of body modification. This is audience guidance, not an official ESRB or PEGI classification.</p><h3>A living independent game</h3><p>Sixteen chapters, eight life phases, and level-80 progression. The campaign targets 10–14 hours on Standard difficulty; actual duration depends on reading, strategy, and exploration. AAA production quality and a measured ten-hour minimum are not claimed.</p><p class="panel-note">Original code and original assets: MIT. The license does not grant rights to the underlying Red Rising intellectual property. Full dependency and font notices are included with the source.</p></div>`;
}

export function endingContent(state: GameState): string {
  const ending = ENDINGS[state.ending ?? 'common-dawn'];
  return `<div class="ending-modal"><div class="ending-sigil">${wolfMark()}</div><span class="eyebrow">THE END OF ONE STORY</span><h2>${ending.title}</h2><p>${ending.text}</p><div class="ending-stats"><div><strong>64</strong><span>OPERATIONS</span></div><div><strong>${levelOf(state)}</strong><span>LEVEL</span></div><div><strong>${state.victories}</strong><span>VICTORIES</span></div></div><p class="panel-note">Your life continues. Patrol the roads, strengthen your bonds, complete your equipment, and reach level 80.</p>${button('Return to the Hollow', 'ending-close', { className: 'primary full-width', icon: 'camp' })}</div>`;
}

export function companionContent(state: GameState): string {
  return `<span class="eyebrow">THE PEOPLE WHO STAY</span><h2>Choose your companion</h2><p>Each companion brings a different support ability. A stronger bond improves its effect.</p><div class="companion-choices">${COMPANIONS.map(companion => {
    const unlocked = companion.id === ORIGINS[state.origin].companion || state.completed.filter(id => id.startsWith('c')).length >= Math.max(16, companion.unlock);
    return `<button class="companion-choice ${state.companion === companion.id ? 'selected' : ''}" data-action="companion-select" data-companion="${companion.id}" ${!unlocked || Boolean(state.battle) ? 'disabled' : ''}><img src="${companionSprite(companion.color).toDataURL()}" alt=""><div><span class="eyebrow">${companion.role.toUpperCase()}</span><strong>${companion.name}</strong><p>${companion.description}</p><small>${unlocked ? `${companion.skill} · Bond ${state.bonds[companion.id] ?? 0}/100` : 'Joins after the origins converge in Chapter 4.'}</small></div>${icon(state.companion === companion.id ? 'check' : unlocked ? 'arrow' : 'lock')}</button>`;
  }).join('')}</div><p class="panel-note">Talk at camp and complete expeditions together to build trust.</p>`;
}
